version: 0.0
os: linux
files:
    - source: /
      destination: /home/lotusinterworks.internal/yahyas/createode
hooks:
  AfterInstall:
    - location: stop.sh
  ApplicationStart:
    - location: start.sh