version: 0.0
os: linux
files:
    - source: /
      destination: /home/lotusinterworks.internal/yahyas/codedeploy
hooks:
  AfterInstall:
    - location: stop.sh
      runas: yahyas@lotusinterworks.internal
  ApplicationStart:
    - location: start.sh
      runas: yahyas@lotusinterworks.internal

