version: 0.0
os: linux
files:
    - source: /
      destination: /home/lotusinterworks.internal/yahyas
hooks:
  AfterInstall:
    - location: /home/lotusinterworks.internal/yahyas/stop.sh
      runas: yahyas@lotusinterworks.internal
  ApplicationStart:
    - location: /home/lotusinterworks.internal/yahyas/start.sh
      runas: yahyas@lotusinterworks.internal

