version: 0.0
os: linux
files:
    - source: /
      destination: /home/lotusinterworks.internal/yahyas
hooks:
  AfterInstall:
    - location: stop.sh
      runas: yahyas
  ApplicationStart:
    - location: start.sh
      runas: yahyas

