version: 0.0
os: linux
files:
    - source: /
      destination: /home/ec2-user/simpleApp
hooks:
  #AfterInstall:
  # - location: stop.sh
  #   runas: ec2-user
  ApplicationStart:
    - location: start.sh
      runas: ec2-user

